#!/usr/bin/env bash
# ============================================================
# build.sh — Assemble the modular sources in lib/ and modules/
# into a single, self-contained, runnable setup.sh.
#
# The committed setup.sh is GENERATED by this script. Edit the
# files under lib/ and modules/, then run:  bash build.sh
#
# Why a single-file artifact?  It keeps the one-liner install
# (bash <(curl .../setup.sh)) and the in-script self-update
# (menu 15 / check_update) working without any extra files.
# ============================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

OUT="setup.sh"
TMP="$(mktemp)"

# Assembly order. Function-definition order is irrelevant in bash
# (everything is defined before the entry block runs); this order is
# chosen only for human readability of the generated file.
FILES=(
  lib/common.sh
  lib/detect.sh
  lib/i18n.sh
  modules/init.sh
  modules/firewall.sh
  modules/cert.sh
  modules/deploy_wordpress.sh
  modules/deploy_xboard.sh
  modules/deploy_3xui.sh
  modules/security.sh
  modules/system_info.sh
  modules/docker.sh
  modules/backup.sh
  modules/network.sh
  modules/cleanup.sh
  modules/update.sh
  modules/menu.sh
)

{
  echo "#!/bin/bash"
  echo "# ============================================================"
  echo "#  GENERATED FILE — DO NOT EDIT BY HAND."
  echo "#  Edit lib/*.sh and modules/*.sh, then run: bash build.sh"
  echo "# ============================================================"
  echo ""

  for f in "${FILES[@]}"; do
    if [ ! -f "$f" ]; then
      echo "build.sh: missing source $f" >&2
      exit 1
    fi
    echo "# ----- $f -----"
    # Strip per-fragment shebangs and shellcheck shell directives so
    # they don't end up scattered through the assembled file.
    sed -e '/^#!/d' -e '/^# shellcheck shell=bash$/d' "$f"
    echo ""
  done

  # Entry point — runs after every function is defined.
  echo "# ============================================================"
  echo "# 入口 / Entry point"
  echo "# ============================================================"
  echo "check_root"
  echo "select_language"
  echo "detect_os"
  echo "check_installed"
  echo "main_menu"
} > "$TMP"

# Normalise to LF (the original was CRLF, which can break execution
# on some Linux shells) and write the artifact.
sed 's/\r$//' "$TMP" > "$OUT"
rm -f "$TMP"
chmod +x "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines) from ${#FILES[@]} source files."
